# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - ps: "npm t # PowerShell"
  - cmd: npm t

os:
  - Default Azure
  - Windows Server 2012 R2

build: off

version: "{build}"
